language: c
compiler:
    - gcc
    - clang
before_install:
    - pip install --user cpp-coveralls
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        export CC="gcc-4.7";
        export CXX="g++-4.7";
        export LINK="gcc-4.7";
        export LINKXX="g++-4.7";
        fi
script:
    - cmake . && make && make test
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
