language: c
compiler:
    - gcc
    - clang
before_install:
    - pip install --user cpp-coveralls
script:
    - cmake . && make && make test
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
