language: c
compiler:
    - gcc
    - clang
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      - gettext
      - libintl
before_install:
    - pip install --user cpp-coveralls
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        export CC="gcc-4.7";
        export CXX="g++-4.7";
        export LINK="gcc-4.7";
        export LINKXX="g++-4.7";
        fi
    - gcc --version
    - g++ --version
script:
    - cmake . && make
    - cd bin 
    - ./latino ../ejemplos/coverage.lat
    - gcov ../src/latino.c --object-directory ../src/CMakeFiles/latino.dir/
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
